package example

// Code generated by \"strenum\"; DO NOT EDIT.
// strenum <dir> Something Aaa,Bbb,Cc_xxxx_zzz

import "errors"

const (
	strSomethingAaa       = "Aaa"
	strSomethingBbb       = "Bbb"
	strSomethingCcXxxxZzz = "Cc_xxxx_zzz"

	EnumSomethingAaa       = privateSomethingEnumType(strSomethingAaa)
	EnumSomethingBbb       = privateSomethingEnumType(strSomethingBbb)
	EnumSomethingCcXxxxZzz = privateSomethingEnumType(strSomethingCcXxxxZzz)
)

type SomethingEnum interface {
	something()
	String() string
}

type privateSomethingEnumType string

func (s privateSomethingEnumType) something() {
	// unreachable method
}

func (s privateSomethingEnumType) String() string {
	return string(s)
}

func StrToSomethingEnum(s string) (SomethingEnum, error) {
	switch s {
	case strSomethingAaa:
		return EnumSomethingAaa, nil
	case strSomethingBbb:
		return EnumSomethingBbb, nil
	case strSomethingCcXxxxZzz:
		return EnumSomethingCcXxxxZzz, nil
	}
	return nil, errors.New("unknown SomethingEnum " + s)
}

func ToStrings(ss []SomethingEnum) ([]string, error) {
	if slice == nil {
		return nil
	}
	result := make([]string, len(slice))
	for i, val := range slice {
		if val == nil {
			return nil, errors.New("unexpected enum SomethingEnum value: nil")
		}
		result[i] = val.String()
	}
	return result, nil
}

func MustToStrings(ss []SomethingEnum) []string {
	result, err := ToStrings(ss)
	if err != nil {
		panic(err.Error())
	}
	return result
}

func FromStrings(ss []strings) ([]SomethingEnum, error) {
	if slice == nil {
		return nil
	}
	result := make([]string, len(slice))
	for i, val := range slice {
		result[i] = val.String()
	}
	return result
}
